import type { Servizio } from "./servizi";

/** Scuole e spot windsurf/kite (dati da elenco Google Maps). */
export const serviziWindsurfKite: readonly Servizio[] = [
  {
    name: "Dolphin Windsurf",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Dolphin+Windsurf,+Porto+Pollo",
    rating: 4.8,
    reviews: 33,
    description: "Luca e un istruttore cordiale e molto bravo con i ragazzi.",
  },
  {
    name: "Club Nautico La Maddalena",
    category: "Windsurf kite",
    zona: "Padule",
    coordinates: [9.4308615, 41.2240530],
    url: "https://maps.google.com/?q=Club+Nautico+La+Maddalena,+Localita+la+Ricciolina,+La+Maddalena",
    rating: 5.0,
    reviews: 11,
    description: "Ambiente super consigliato.",
  },
  {
    name: "Saltywind, Windsuf Sailing Sup Surf Center",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Saltywind+Windsurf+Sailing+Sup+Surf+Center,+Spiaggia+La+Sciumara",
    rating: 4.8,
    reviews: 45,
    description: "Noleggio windsurf, sup e canoe.",
  },
  {
    name: "Associazione Acque Libere",
    category: "Windsurf kite",
    zona: "Centro Storico",
    coordinates: [9.4074965, 41.2136245],
    url: "https://maps.google.com/?q=Associazione+Acque+Libere,+Via+Ammiraglio+Mirabello+27,+La+Maddalena",
    rating: 5.0,
    reviews: 5,
    description: "Ottima scuola, bravissimi tutti.",
  },
  {
    name: "MB Pro Center",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=MB+Pro+Center,+Localita+Porto+Pollo+1",
    rating: 4.2,
    reviews: 155,
    description: "Attrezzatura al top per windsurf e wing foil.",
  },
  {
    name: "Buenaondasurf - Scuola Winsurf e Vela, Escursioni in Barca e Noleggio",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Buenaondasurf,+Porto+Pollo",
    rating: 4.9,
    reviews: 114,
    description: "Primo approccio al windsurf con team molto preparato.",
  },
  {
    name: "Scuola Windsurf - Kitesurf Portopollo.it RUPI'S",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Scuola+Windsurf+Kitesurf+Portopollo+RUPI%27S,+Via+per+campeggio",
    rating: 4.4,
    reviews: 150,
    description: "Corsi individuali e di gruppo.",
  },
  {
    name: "FH Academy",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=FH+Academy,+Strada+per+Isola+dei+Gabbiani",
    rating: 4.8,
    reviews: 126,
    description: "Spot stupendo e istruttori pazienti e competenti.",
  },
  {
    name: "Club Porto Liscia Windsurf",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Club+Porto+Liscia+Windsurf,+Spiaggia+di+Porto+Liscia",
    rating: 4.5,
    reviews: 195,
    description: "Luogo ideale per imparare windsurf e wingfoil.",
  },
  {
    name: "Windsurf Village Baia dei Delfini",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Windsurf+Village+Baia+dei+Delfini,+Via+Tramontana+47",
    rating: 4.2,
    reviews: 148,
    description: "Struttura collegata ai principali spot vento.",
  },
  {
    name: "Noleggio Gommoni La Maddalena On Board",
    category: "Windsurf kite",
    zona: "Padule",
    coordinates: [9.4308615, 41.2240530],
    url: "https://maps.google.com/?q=Noleggio+Gommoni+La+Maddalena+On+Board,+Via+Padule,+La+Maddalena",
    rating: 4.6,
    reviews: 78,
    description: "Ottima organizzazione, puntualita e disponibilita.",
  },
  {
    name: "SurfStar center Porto Pollo",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=SurfStar+center+Porto+Pollo,+Localita+Angolo+Azzurro",
    rating: 4.3,
    reviews: 6,
    description: "Centro wingfoil e windsurf attrezzato.",
  },
  {
    name: "Wind Water Sport Center Porto Pollo",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Wind+Water+Sport+Center+Porto+Pollo,+Via+per+campeggio",
    rating: 4.8,
    reviews: 163,
    description: "Per iniziare o perfezionarsi nel windsurf.",
  },
  {
    name: "Extreme Sail A.S.D. - Scuola Windsurf , Wing foil , Catamarani e Derive - Marinella",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Extreme+Sail+ASD+Marinella,+Golfo+di+Marinella",
    rating: 5.0,
    reviews: 53,
    description: "Scuola completa per windsurf e wing foil.",
  },
  {
    name: "Porto Pollo Island Experience",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Porto+Pollo+Island+Experience,+Porto+Pollo",
    rating: 4.6,
    reviews: 45,
    description: "Ottima professionalita degli insegnanti.",
  },
  {
    name: "Wind Kite surf zone Portopollo",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Wind+Kite+surf+zone+Portopollo,+SP98",
    rating: 5.0,
    reviews: 2,
    description: "Scuola specializzata in kite e windsurf.",
  },
  {
    name: "Jungle Surf",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Jungle+Surf,+Via+Nazionale+116",
    rating: 4.4,
    reviews: 158,
    description: "Negozio di riferimento per amanti del windsurf.",
  },
  {
    name: "I W D",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=I+W+D,+Porto+Pollo",
    rating: 4.0,
    reviews: 1,
    description: "Scuola di vela e sport acquatici.",
  },
  {
    name: "Blue Zone Sardinia",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Blue+Zone+Sardinia,+Camping+Baia+Blu+la+Tortuga+Vignola+Mare",
    rating: 4.8,
    reviews: 89,
    description: "Esperienza sportiva completa per sport del vento.",
  },
  {
    name: "Sporting Club Sardinia (Sailing Center)",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    coordinates: [9.3824493, 41.1816219],
    url: "https://maps.google.com/?q=Sporting+Club+Sardinia+Sailing+Center,+Porto+Pollo",
    rating: 4.5,
    reviews: 76,
    description: "Spiaggia attrezzata con scuola vela e windsurf.",
  },
].map((servizio) => ({ isFavorite: false, maddiNote: "", ...(servizio as Servizio) }));