import type { Servizio } from "./servizi";

/** Servizi vela (dati da elenco Google Maps). */
export const serviziVela: readonly Servizio[] = [
  {
    name: "Club Nautico La Maddalena",
    category: "Vela",
    zona: "Padule",
    coordinates: [9.4308615, 41.2240530],
    url: "https://maps.google.com/?q=Club+Nautico+La+Maddalena,+Localit%C3%A0+la+Ricciolina,+La+Maddalena",
    rating: 5.0,
    reviews: 11,
    description: "Scuola di vela e circolo nautico locale.",
  },
  {
    name: "Associazione Acque Libere",
    category: "Vela",
    zona: "Centro Storico",
    coordinates: [9.4074965, 41.2136245],
    url: "https://maps.google.com/?q=Associazione+Acque+Libere,+Via+Ammiraglio+Mirabello+27,+La+Maddalena",
    rating: 5.0,
    reviews: 5,
    description: "Scuola di vela con base in centro.",
  },
  {
    name: "Centro Velico Caprera",
    category: "Vela",
    zona: "Caprera",
    coordinates: [9.4709183, 41.2294086],
    url: "https://maps.google.com/?q=Centro+Velico+Caprera,+Localit%C3%A0+Punta+Coda,+Caprera",
    rating: 4.7,
    reviews: 98,
    description: "Riferimento storico per corsi vela e regata.",
  },
  {
    name: "Veliero Helena — Gite in barca a vela",
    category: "Vela",
    zona: "Padule",
    coordinates: [9.4308615, 41.2240530],
    url: "https://maps.google.com/?q=Veliero+Helena,+Pontile+il+Porticciolo,+Localit%C3%A0+Padule,+La+Maddalena",
    rating: 4.9,
    reviews: 41,
    description: "Escursioni giornaliere in veliero.",
  },
  {
    name: "Fil Rouge Sail — Gite in barca a vela",
    category: "Vela",
    zona: "Centro Storico",
    coordinates: [9.4074965, 41.2136245],
    url: "https://maps.google.com/?q=Fil+Rouge+Sail,+Via+Oberdan,+La+Maddalena",
    rating: 4.9,
    reviews: 116,
    description: "Uscite a vela con skipper nell'arcipelago.",
  },
  {
    name: "Veliero Dolce Vita La Maddalena",
    category: "Vela",
    zona: "Centro Storico",
    coordinates: [9.4074965, 41.2136245],
    url: "https://maps.google.com/?q=Veliero+Dolce+Vita,+Via+Indipendenza+1,+La+Maddalena",
    rating: 4.9,
    reviews: 172,
    description: "Escursioni giornaliere in veliero.",
  },
  {
    name: "Velieri Valentina",
    category: "Vela",
    zona: "Centro Storico",
    coordinates: [9.4074965, 41.2136245],
    url: "https://maps.google.com/?q=Velieri+Valentina,+Via+Comandante+Avegno+1,+La+Maddalena",
    rating: 4.8,
    reviews: 76,
    description: "Escursioni in veliero nel Parco.",
  },
  {
    name: "JOY Sailing Escursioni La Maddalena",
    category: "Vela",
    zona: "Cala Gavetta",
    coordinates: [9.4057552, 41.2114003],
    url: "https://maps.google.com/?q=JOY+Sailing,+Marina+Mangiavolpe,+Piazza+Umberto+I,+La+Maddalena",
    rating: 4.9,
    reviews: 89,
    description: "Giornate a vela con partenza dal porto.",
  },
  {
    name: "Sea Passion Catamaran Sailing Tours",
    category: "Vela",
    zona: "Cala Gavetta",
    coordinates: [9.4057552, 41.2114003],
    url: "https://maps.google.com/?q=Sea+Passion+catamaran+sailing+tours,+Porto+Turistico,+La+Maddalena",
    rating: 5.0,
    reviews: 378,
    description: "Escursioni in catamarano nell'arcipelago.",
  },
].map((servizio) => ({ isFavorite: false, maddiNote: "", ...(servizio as Servizio) }));