import type { Servizio } from "./servizi";

/** Spiagge dell'arcipelago da elenco utente (senza immagini stock). */
export const serviziSpiagge: readonly Servizio[] = [
  {
    name: "Spiaggia di Cala Spalmatore",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.429379, 41.246826],
    esposizione: ["N", "NE", "E"],
    maddiTip: "Molto bella con Scirocco o Ostro; con Tramontana tende a incresparsi.",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Spalmatore,+La+Maddalena",
    rating: 4.4,
    reviews: 1368,
    description: "Tratto sabbioso con acque cristalline e un bar.",
  },
 
  {
    name: "Spiaggia Monti d'à Rena",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.413742, 41.250664],
    esposizione: ["N", "NW", "W"],
    maddiTip: "Ideale con venti da est (Scirocco/Levante), meno comoda con Maestrale teso.",
    url: "https://maps.google.com/?q=Spiaggia+Monti+d%27a+Rena,+La+Maddalena",
    rating: 4.6,
    reviews: 1022,
  },
  {
    name: "Spiaggia di Punta Tegge",
    category: "Spiagge",
    zona: "Cala Gavetta",
    coordinates: [9.385298, 41.211454],
    esposizione: ["W", "SW", "S"],
    maddiTip: "Molto godibile con Grecale o Tramontana; piu esposta con Libeccio.",
    url: "https://maps.google.com/?q=Spiaggia+di+Punta+Tegge,+Localit%C3%A0+Punta+Tegge+3,+La+Maddalena",
    rating: 4.6,
    reviews: 2390,
    description:
      "Cala rocciosa, spiagge note, immersioni.",
  },
  {
    name: "Spiaggia di Cala Lunga",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.424705, 41.25747],
    esposizione: ["E", "SE"],
    maddiTip: "Rende al meglio con Maestrale; con Levante il mare puo alzarsi.",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Lunga,+Isola+di+La+Maddalena",
    rating: 4.5,
    reviews: 223,
    description: "Isola Maddalena.",
  },
  {
    name: "Spiaggia dello Strangolato",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.404587, 41.257557],
    esposizione: ["N", "NE"],
    maddiTip: "Top con venti meridionali; evita giornate di Tramontana forte.",
    url: "https://maps.google.com/?q=Spiaggia+dello+Strangolato,+La+Maddalena",
    rating: 4.5,
    reviews: 418,
  },
  {
    name: "Spiaggia di Cala Coticcio",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.484475, 41.21884],
    esposizione: ["NE", "E"],
    maddiTip: "Perfetta con Maestrale moderato; con Grecale pieno il mare entra.",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Coticcio,+Caprera",
    rating: 4.7,
    reviews: 2375,
    description: "Caletta suggestiva tra scogliere.",
  },
  {
    name: "Spiaggia di Bassa Trinita",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.39917, 41.241528],
    esposizione: ["NW", "W", "SW"],
    maddiTip: "Funziona bene con Scirocco o Levante; con Maestrale puo essere agitata.",
    url: "https://maps.google.com/?q=Spiaggia+di+Bassa+Trinita,+La+Maddalena",
    rating: 4.7,
    reviews: 1523,
    description:
      "Spiaggia con 3 calette e sentiero naturale.",
  },
  {
    name: "Spiaggia I due Mari",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.464217, 41.183491],
    esposizione: ["E", "W", "NW"],
    maddiTip: "Scegli il lato piu riparato del giorno: in genere ottima con brezze leggere.",
    url: "https://maps.google.com/?q=Spiaggia+I+due+Mari,+Caprera",
    rating: 4.5,
    reviews: 1437,
  },
  {
    name: "Spiaggia Testa del Polpo",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.446922, 41.232056],
    esposizione: ["NE", "E"],
    maddiTip: "Molto piacevole con Maestrale, meno stabile con Levante sostenuto.",
    url: "https://maps.google.com/?q=Spiaggia+Testa+del+Polpo,+La+Maddalena",
    rating: 4.6,
    reviews: 1655,
    description:
      "Tratto di sabbia bianca con scogli affioranti.",
  },
  {
    name: "Spiaggia Cala d'Inferno",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.389706, 41.232864],
    esposizione: ["N", "NW"],
    maddiTip: "Meglio con Scirocco e Ostro; con Tramontana il mare tende a chiudere.",
    url: "https://maps.google.com/?q=Spiaggia+Cala+d%27Inferno,+La+Maddalena",
    rating: 4.1,
    reviews: 57,
  },
  {
    name: "Spiaggia del Costone",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.428466, 41.250967],
    esposizione: ["N", "NW"],
    maddiTip: "Piacevole con venti da sud; meno indicata con Maestrale forte.",
    url: "https://maps.google.com/?q=Spiaggia+del+Costone,+La+Maddalena",
    rating: 4.5,
    reviews: 371,
  },
  {
    name: "Spiaggia del Costone",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.428466, 41.250967],
    esposizione: ["N", "NW"],
    maddiTip: "Consigliata con Scirocco; con Tramontana resta piu ventosa e mossa.",
    url: "https://maps.google.com/?q=Spiaggia+del+Costone,+La+Maddalena",
    rating: 4.5,
    reviews: 371,
    description:
      "Tra le più sottovalutate e meno affollate del versante nord.",
  },
  {
    name: "Spiaggia dell'Alberello",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.443214, 41.231532],
    esposizione: ["NE", "E"],
    maddiTip: "Buona opzione con Maestrale; meno riparata con Levante pieno.",
    url: "https://maps.google.com/?q=Spiaggia+dell%27Alberello,+Giardinelli,+La+Maddalena",
    rating: 4.6,
    reviews: 187,
    description: "Località Giardinelli.",
  },
  {
    name: "Spiaggia Punta Rossa Corsara",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.346316, 41.229542],
    esposizione: ["N", "NE"],
    maddiTip: "Fantastica con Scirocco leggero; con Grecale forte aumenta il moto ondoso.",
    url: "https://maps.google.com/?q=Spiaggia+Punta+Rossa+Corsara,+Strada+Padulacciu,+La+Maddalena",
    rating: 4.7,
    reviews: 141,
  },
  {
    name: "Spiaggia del Cardellino",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.415372, 41.254448],
    esposizione: ["NE", "E"],
    maddiTip: "Ottima con Maestrale moderato; piu esposta con Levante.",
    url: "https://maps.google.com/?q=Spiaggia+del+Cardellino,+La+Maddalena",
    rating: 4.6,
    reviews: 504,
    description: "Isola Maddalena.",
  },
  {
    name: "Spiaggia dei marinai",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.444098, 41.234261],
    esposizione: ["E", "SE"],
    maddiTip: "Piacevole con Maestrale o Ponente; con Scirocco forte risulta piu mossa.",
    url: "https://maps.google.com/?q=Spiaggia+dei+marinai,+La+Maddalena",
    rating: 4.6,
    reviews: 15,
    description: "Unnamed Road, 07024.",
  },
  {
    name: "Spiaggia La Scogliera",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.412689, 41.249622],
    esposizione: ["E", "SE"],
    maddiTip: "Meglio con Maestrale e Tramontana; con Levante puo diventare piu impegnativa.",
    url: "https://maps.google.com/?q=Spiaggia+La+Scogliera,+La+Maddalena",
    rating: 4.5,
    reviews: 15,
  },
  {
    name: "Spiaggia di Cala Garibaldi",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.458273, 41.222517],
    esposizione: ["S", "SW"],
    maddiTip: "Perfetta con Tramontana/Grecale; meno riparata quando soffia Scirocco.",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Garibaldi,+Caprera",
    rating: 4.2,
    reviews: 845,
  },
  {
    name: "Spiaggia Bassa Trinità",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.39917, 41.241528],
    esposizione: ["NW", "W", "SW"],
    maddiTip: "Scelta ottima con Levante; con Maestrale forte si forma onda.",
    url: "https://maps.google.com/?q=Spiaggia+Bassa+Trinit%C3%A0,+La+Maddalena",
    rating: 4.7,
    reviews: 278,
  },
  {
    name: "Spiaggia di Cala Andreani",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.470752, 41.176851],
    esposizione: ["E", "SE"],
    maddiTip: "Molto godibile con venti da ovest; con Levante resta piu esposta.",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Andreani,+Caprera",
    rating: 4.8,
    reviews: 75,
  },
  {
    name: "Spiaggia di Porto Palma",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.450406, 41.193285],
    esposizione: ["S", "SE"],
    maddiTip: "Migliore con Maestrale e Tramontana; con Scirocco puo incresparsi presto.",
    url: "https://maps.google.com/?q=Spiaggia+di+Porto+Palma,+Caprera",
    rating: 4.6,
    reviews: 233,
  },
  {
    name: "Spiaggia del Relitto",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.475381, 41.18105],
    esposizione: ["E", "SE"],
    maddiTip: "Ottima con Maestrale e Ponente; con Levante pieno il mare entra.",
    url: "https://maps.google.com/?q=Spiaggia+del+Relitto,+Caprera",
    description: "Spiaggia iconica di Caprera con sabbia chiara e acqua trasparente.",
  },
  {
    name: "Doggie Beach",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.455994, 41.186758],
    esposizione: ["SE", "S"],
    maddiTip: "Comoda con Maestrale e Tramontana; con Scirocco puo essere piu mossa.",
    url: "https://maps.google.com/?q=Doggie+Beach,+Caprera",
    description: "Spiaggia pet-friendly in area Caprera, adatta anche a chi viaggia con cani.",
  },
  {
    name: "Cala Napoletana",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.463338, 41.242065],
    esposizione: ["NE", "E"],
    maddiTip: "Molto bella con Maestrale moderato; con Levante forte entra onda.",
    url: "https://maps.google.com/?q=Cala+Napoletana,+Caprera",
    description: "Piccola cala con mare limpido e fondali trasparenti.",
  },
  {
    name: "Cala Caprarese",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.463167, 41.237632],
    esposizione: ["NE", "E"],
    maddiTip: "Rende bene con venti da ovest; con Grecale sostenuto resta piu esposta.",
    url: "https://maps.google.com/?q=Cala+Caprarese,+Caprera",
    description: "Cala raccolta e scenografica nel tratto orientale dell'arcipelago.",
  },
  {
    name: "Cala Serena",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.460342, 41.227081],
    esposizione: ["E", "SE"],
    maddiTip: "Ottima con Maestrale e Ponente; con Levante puo risultare piu viva.",
    url: "https://maps.google.com/?q=Cala+Serena,+La+Maddalena",
    description: "Caletta tranquilla in zona Giardinelli, acqua chiara e fondali bassi.",
  },
  {
    name: "Spiaggia dei Giardinelli",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.444098, 41.234261],
    esposizione: ["SE", "S"],
    maddiTip: "Funziona bene con Tramontana; con Scirocco forte tende a incresparsi.",
    url: "https://maps.google.com/?q=Spiaggia+di+Giardinelli,+La+Maddalena",
    description: "Spiaggia ampia in area Giardinelli, con accesso semplice e acqua turchese.",
  },
  {
    name: "Spiaggia del Villaggio Piras",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.434324, 41.237493],
    esposizione: ["E", "SE"],
    maddiTip: "Piacevole con venti da ovest; meno riparata durante Levante pieno.",
    url: "https://maps.google.com/?q=Spiaggia+del+Villaggio+Piras,+La+Maddalena",
    description: "Piccola spiaggia sotto Villaggio Piras, ideale per soste brevi.",
  },
  {
    name: "Spiaggia Nido d'Aquila",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.383212, 41.216569],
    esposizione: ["W", "SW"],
    maddiTip: "Molto valida con Grecale e Tramontana; con Libeccio puo essere piu mossa.",
    url: "https://maps.google.com/?q=Spiaggia+Nido+d%27Aquila,+La+Maddalena",
    description: "Baia panoramica in area Cala Francese, tra scogli e acqua trasparente.",
  },
  {
    name: "Cala Corsara",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.343941, 41.231018],
    esposizione: ["S", "SE"],
    maddiTip: "Perfetta con Maestrale moderato; con Scirocco teso tende a incresparsi.",
    url: "https://maps.google.com/?q=Cala+Corsara,+Spargi",
    description: "La cala piu iconica di Spargi, sabbia chiara e acqua turchese.",
  },
  {
    name: "Cala Soraja",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.350784, 41.231522],
    esposizione: ["SE", "S"],
    maddiTip: "Molto piacevole con venti da nord; meno riparata con Scirocco pieno.",
    url: "https://maps.google.com/?q=Cala+Soraja,+Spargi",
    description: "Caletta di Spargi poco ampia, ideale per soste in barca.",
  },
  {
    name: "Cala Granara",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.354304, 41.23482],
    esposizione: ["E", "SE"],
    maddiTip: "Rende bene con Maestrale e Ponente; con Levante resta piu esposta.",
    url: "https://maps.google.com/?q=Cala+Granara,+Spargi",
    description: "Spiaggia di Spargi con fondali bassi e sabbia molto chiara.",
  },
  {
    name: "Cala Ferrigno",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.355985, 41.244644],
    esposizione: ["N", "NE"],
    maddiTip: "Ottima con venti meridionali; con Tramontana forte puo chiudersi.",
    url: "https://maps.google.com/?q=Cala+Ferrigno,+Spargi",
    description: "Conosciuta anche come Canniccio, tra le cale piu selvagge di Spargi.",
  },
  {
    name: "Spiaggia Rosa",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.356103, 41.279331],
    esposizione: ["NE", "E"],
    maddiTip: "Da ammirare solo da lontano: area protetta e balneazione non consentita.",
    url: "https://maps.google.com/?q=Spiaggia+Rosa,+Budelli",
    description: "La celebre spiaggia di Budelli, tutelata dal Parco e non accessibile alla balneazione.",
  },
  {
    name: "Spiaggia del Cavaliere",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.358951, 41.286268],
    esposizione: ["N", "NE", "E"],
    maddiTip: "Acqua spesso calma nel Porto della Madonna; verifica sempre restrizioni del Parco.",
    url: "https://maps.google.com/?q=Spiaggia+del+Cavaliere,+Budelli",
    description: "Linguetta chiara tra Budelli, Razzoli e Santa Maria nel Porto della Madonna.",
  },
  {
    name: "Spiaggia di Santa Maria",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.370773, 41.293814],
    esposizione: ["N", "NE"],
    maddiTip: "Molto gradevole con brezze da sud; con Tramontana puo risultare piu ventosa.",
    url: "https://maps.google.com/?q=Spiaggia+di+Santa+Maria,+Isola+di+Santa+Maria",
    description: "Spiaggia principale dell'isola di Santa Maria, sabbia chiara e mare trasparente.",
  },
  {
    name: "La Maddalena Spiaggia",
    category: "Spiagge",
    zona: "Cala Gavetta",
    coordinates: [9.401898, 41.247632],
    esposizione: ["S", "SW"],
    maddiTip: "Comoda con venti da nord; con Libeccio risente di piu del moto ondoso.",
    url: "https://maps.google.com/?q=La+Maddalena+Spiaggia,+La+Maddalena",
    rating: 3.9,
    reviews: 275,
  },
  {
    name: "Spiaggia di Ricciolina",
    category: "Spiagge",
    zona: "Padule",
    coordinates: [9.430223, 41.230494],
    esposizione: ["E", "SE", "S"],
    maddiTip: "Buona con Maestrale; con Scirocco teso tende a essere meno confortevole.",
    url: "https://maps.google.com/?q=Spiaggia+di+Ricciolina,+Localit%C3%A0+la+Ricciolina,+La+Maddalena",
    rating: 3.2,
    reviews: 13,
  },
  {
    name: "Cala Andreani",
    category: "Spiagge",
    zona: "Caprera",
    coordinates: [9.470752, 41.176851],
    esposizione: ["E", "SE"],
    maddiTip: "Consigliata con Ponente o Maestrale; con Levante il mare entra di piu.",
    url: "https://maps.google.com/?q=Cala+Andreani,+Caprera",
    rating: 4.7,
    reviews: 1265,
  },
  {
    name: "Spiaggia di Abbatoggia",
    category: "Spiagge",
    zona: "Moneta",
    coordinates: [9.4059, 41.255],
    esposizione: ["W", "NW"],
    maddiTip: "Perfetta con Scirocco; con Maestrale forte risulta piu ventosa e ondosa.",
    url: "https://maps.google.com/?q=Spiaggia+di+Abbatoggia,+La+Maddalena",
    rating: 4.3,
    reviews: 35,
  },
]
  .map((servizio) => ({ isFavorite: false, maddiNote: "", ...(servizio as Servizio) }))
  .reduce<Servizio[]>((acc, servizio) => {
    if (acc.some((item) => {
      if (!Array.isArray(item.coordinates) || !Array.isArray(servizio.coordinates)) {
        return item.name.toLowerCase() === servizio.name.toLowerCase();
      }
      return (
        item.coordinates[0].toFixed(6) === servizio.coordinates[0].toFixed(6) &&
        item.coordinates[1].toFixed(6) === servizio.coordinates[1].toFixed(6)
      );
    })) {
      return acc;
    }
    // Memorizziamo la prima occorrenza per mantenere ordine e contenuti coerenti.
    acc.push(servizio);
    return acc;
  }, []);
