import type { Servizio } from "./servizi";

/** Gelaterie (dati da elenco Google Maps). */
export const serviziGelaterie: readonly Servizio[] = [
  {
    name: "Gelateria La Finestrella",
    category: "Gelaterie",
    zona: "Centro Storico",
    coordinates: [9.4078176, 41.2137720],
    url: "https://maps.google.com/?q=Gelateria+La+Finestrella,+Via+Amendola+11,+La+Maddalena",
    rating: 4.8,
    reviews: 1294,
    isFavorite: true,
    maddiNote: "Le signore al banco sono simpaticissime e il gelato è delizioso",
  },
  {
    name: "Gelatissimo",
    category: "Gelaterie",
    zona: "Centro Storico",
    coordinates: [9.4082192, 41.2141569],
    url: "https://maps.google.com/?q=Gelatissimo,+Via+Amendola+45,+La+Maddalena",
    rating: 4.7,
    reviews: 659,
  },
  {
    name: "Dolci Distrazioni — Via Amendola",
    category: "Gelaterie",
    zona: "Centro Storico",
    coordinates: [9.4058046, 41.2131294],
    url: "https://maps.google.com/?q=Dolci+Distrazioni,+Via+Giorgio+Amendola+35,+La+Maddalena",
    rating: 4.7,
    reviews: 59,
    isFavorite: true,
    maddiNote: "Ottimo il gelato di Dolci Distrazioni anche se e cambiata la proprietaria.",
  },
  {
    name: "Gelateria Ilva",
    category: "Gelaterie",
    zona: "Centro Storico",
    coordinates: [9.4078176, 41.2137720],
    url: "https://maps.google.com/?q=Gelateria+Ilva,+Piazza+Umberto+I+1,+La+Maddalena",
    rating: 4.0,
    reviews: 118,
  },
  {
    name: "Gelateria Gelatomania",
    category: "Gelaterie",
    zona: "Centro Storico",
    coordinates: [9.4078176, 41.2137720],
    url: "https://maps.google.com/?q=Gelateria+Gelatomania,+Via+Giuseppe+Garibaldi+82,+La+Maddalena",
    rating: 2.6,
    reviews: 37,
  },
  {
    name: "Crema&Cioccolato",
    category: "Gelaterie",
    zona: "Centro Storico",
    coordinates: [9.4049888, 41.2125027],
    url: "https://maps.google.com/?q=Crema%26Cioccolato,+Via+XX+Settembre,+La+Maddalena",
    rating: 3.0,
    reviews: 42,
  },
  {
    name: "YO ciok",
    category: "Gelaterie",
    zona: "Centro Storico",
    coordinates: [9.4074965, 41.2136245],
    url: "https://maps.google.com/?q=YO+ciok,+Via+Giuseppe+Garibaldi,+La+Maddalena",
    rating: 3.0,
    reviews: 58,
  },
  {
    name: "Dolci Distrazioni — Largo Matteotti (chiuso temporaneamente)",
    category: "Gelaterie",
    zona: "Centro Storico",
    coordinates: [9.4074965, 41.2136245],
    url: "https://maps.google.com/?q=Dolci+Distrazioni,+Largo+Giacomo+Matteotti+8,+La+Maddalena",
    rating: 4.7,
    reviews: 831,
  },
].map((servizio) => ({ isFavorite: false, maddiNote: "", ...(servizio as Servizio) }));