// Client-safe — no Node.js imports.
import { serviziMercati } from "./serviziMercati";
import { serviziMusei } from "./serviziMusei";
import { serviziSentieriCaprera } from "./serviziSentieriCaprera";
import { serviziSpiagge } from "./serviziSpiagge";
import { serviziBanche } from "./serviziBanche";
import { serviziFarmacie } from "./serviziFarmacie";
import { serviziSupermercati } from "./serviziSupermercati";
import { serviziEmergenze } from "./serviziEmergenze";
import { serviziTrasporti } from "./serviziTrasporti";

export const zone = [
  "Centro Storico",
  "Cala Gavetta",
  "Padule",
  "Pueblo / Due Strade",
  "Moneta",
  "Caprera",
  "Porto Pollo / Palau",
] as const;

export type Zona = (typeof zone)[number];

export const categorieServizi = [
  "Supermercati",
  "Farmacie",
  "Spiagge",
  "Vela",
  "Diving",
  "Windsurf kite",
  "Gelaterie",
  "Noleggio gommoni",
  "Noleggio scooter e bike",
  "Banche & ATM",
  "Mercato",
  "Trasporti",
  "Emergenze",
  "Musei",
  "Sentieri Caprera",
] as const;

export type CategoriaServizio = (typeof categorieServizi)[number];

export type Servizio = {
  name: string;
  category: CategoriaServizio;
  zona: Zona;
  /** Coordinates in [longitude, latitude]. */
  coordinates?: [number, number];
  /** Cardinal winds the beach is exposed to (e.g. N, NW, W). */
  esposizione?: string[];
  /** Local tip based on wind exposure. */
  maddiTip?: string;
  /** Google Maps short or full URL */
  url?: string;
  /** Optional public rating shown in card (e.g. 4.4). */
  rating?: number;
  /** Optional number of reviews paired with rating. */
  reviews?: number;
  /** Short teaser (used e.g. for Spiagge cards). */
  description?: string;
  /** Card thumbnail: `/images/...` under `public` or `https://` URL. */
  image?: string;
};

export const servizi: readonly Servizio[] = [
  // ─── Supermercati ────────────────────────────────────────────────────────────
  ...serviziSupermercati,

  // ─── Mercato ─────────────────────────────────────────────────────────────────
  ...serviziMercati,

  // ─── Farmacie ────────────────────────────────────────────────────────────────
  ...serviziFarmacie,

  // ─── Spiagge ────────────────────────────────────────────────────────────────
  ...serviziSpiagge,

  // ─── Vela ───────────────────────────────────────────────────────────────────
  {
    name: "Club Nautico La Maddalena",
    category: "Vela",
    zona: "Padule",
    url: "https://maps.google.com/?q=Club+Nautico+La+Maddalena,+Localit%C3%A0+la+Ricciolina,+La+Maddalena",
    rating: 5.0,
    reviews: 11,
    description: "Scuola di vela e circolo nautico locale.",
  },
  {
    name: "Associazione Acque Libere",
    category: "Vela",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Associazione+Acque+Libere,+Via+Ammiraglio+Mirabello+27,+La+Maddalena",
    rating: 5.0,
    reviews: 5,
    description: "Scuola di vela con base in centro.",
  },
  {
    name: "Centro Velico Caprera",
    category: "Vela",
    zona: "Caprera",
    url: "https://maps.google.com/?q=Centro+Velico+Caprera,+Localit%C3%A0+Punta+Coda,+Caprera",
    rating: 4.7,
    reviews: 98,
    description: "Riferimento storico per corsi vela e regata.",
  },
  {
    name: "Veliero Helena — Gite in barca a vela",
    category: "Vela",
    zona: "Padule",
    url: "https://maps.google.com/?q=Veliero+Helena,+Pontile+il+Porticciolo,+Localit%C3%A0+Padule,+La+Maddalena",
    rating: 4.9,
    reviews: 41,
    description: "Escursioni giornaliere in veliero.",
  },
  {
    name: "Fil Rouge Sail — Gite in barca a vela",
    category: "Vela",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Fil+Rouge+Sail,+Via+Oberdan,+La+Maddalena",
    rating: 4.9,
    reviews: 116,
    description: "Uscite a vela con skipper nell'arcipelago.",
  },
  {
    name: "Veliero Dolce Vita La Maddalena",
    category: "Vela",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Veliero+Dolce+Vita,+Via+Indipendenza+1,+La+Maddalena",
    rating: 4.9,
    reviews: 172,
    description: "Escursioni giornaliere in veliero.",
  },
  {
    name: "Velieri Valentina",
    category: "Vela",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Velieri+Valentina,+Via+Comandante+Avegno+1,+La+Maddalena",
    rating: 4.8,
    reviews: 76,
    description: "Escursioni in veliero nel Parco.",
  },
  {
    name: "JOY Sailing Escursioni La Maddalena",
    category: "Vela",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=JOY+Sailing,+Marina+Mangiavolpe,+Piazza+Umberto+I,+La+Maddalena",
    rating: 4.9,
    reviews: 89,
    description: "Giornate a vela con partenza dal porto.",
  },
  {
    name: "Sea Passion Catamaran Sailing Tours",
    category: "Vela",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Sea+Passion+catamaran+sailing+tours,+Porto+Turistico,+La+Maddalena",
    rating: 5.0,
    reviews: 378,
    description: "Escursioni in catamarano nell'arcipelago.",
  },

  // ─── Diving ────────────────────────────────────────────────────────────────
  {
    name: "La Maddalena Diving ASD",
    category: "Diving",
    zona: "Moneta",
    url: "https://maps.google.com/?q=La+Maddalena+Diving+ASD,+Localit%C3%A0+Punta+Tegge+3,+La+Maddalena",
    rating: 4.5,
    reviews: 56,
    description: "Grande professionalita ed esperienza.",
  },
  {
    name: "AREA11 DIVING CENTER",
    category: "Diving",
    zona: "Padule",
    url: "https://maps.google.com/?q=AREA11+DIVING+CENTER,+Via+Padule+100,+La+Maddalena",
    rating: 4.5,
    reviews: 86,
    description: "Professionalita, cortesia e simpatia.",
  },
  {
    name: "Diving Argonauta La Maddalena",
    category: "Diving",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Diving+Argonauta+La+Maddalena,+La+Maddalena",
    rating: 5.0,
    reviews: 75,
    description: "In grado di metterti a tuo agio e farti sentire sicuro.",
  },

  // ─── Windsurf kite ──────────────────────────────────────────────────────────
  {
    name: "Dolphin Windsurf",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Dolphin+Windsurf,+Porto+Pollo",
    rating: 4.8,
    reviews: 33,
    description: "Luca e un istruttore cordiale e molto bravo con i ragazzi.",
  },
  {
    name: "Club Nautico La Maddalena",
    category: "Windsurf kite",
    zona: "Padule",
    url: "https://maps.google.com/?q=Club+Nautico+La+Maddalena,+Localita+la+Ricciolina,+La+Maddalena",
    rating: 5.0,
    reviews: 11,
    description: "Ambiente super consigliato.",
  },
  {
    name: "Saltywind, Windsuf Sailing Sup Surf Center",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Saltywind+Windsurf+Sailing+Sup+Surf+Center,+Spiaggia+La+Sciumara",
    rating: 4.8,
    reviews: 45,
    description: "Noleggio windsurf, sup e canoe.",
  },
  {
    name: "Associazione Acque Libere",
    category: "Windsurf kite",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Associazione+Acque+Libere,+Via+Ammiraglio+Mirabello+27,+La+Maddalena",
    rating: 5.0,
    reviews: 5,
    description: "Ottima scuola, bravissimi tutti.",
  },
  {
    name: "MB Pro Center",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=MB+Pro+Center,+Localita+Porto+Pollo+1",
    rating: 4.2,
    reviews: 155,
    description: "Attrezzatura al top per windsurf e wing foil.",
  },
  {
    name: "Buenaondasurf - Scuola Winsurf e Vela, Escursioni in Barca e Noleggio",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Buenaondasurf,+Porto+Pollo",
    rating: 4.9,
    reviews: 114,
    description: "Primo approccio al windsurf con team molto preparato.",
  },
  {
    name: "Scuola Windsurf - Kitesurf Portopollo.it RUPI'S",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Scuola+Windsurf+Kitesurf+Portopollo+RUPI%27S,+Via+per+campeggio",
    rating: 4.4,
    reviews: 150,
    description: "Corsi individuali e di gruppo.",
  },
  {
    name: "FH Academy",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=FH+Academy,+Strada+per+Isola+dei+Gabbiani",
    rating: 4.8,
    reviews: 126,
    description: "Spot stupendo e istruttori pazienti e competenti.",
  },
  {
    name: "Club Porto Liscia Windsurf",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Club+Porto+Liscia+Windsurf,+Spiaggia+di+Porto+Liscia",
    rating: 4.5,
    reviews: 195,
    description: "Luogo ideale per imparare windsurf e wingfoil.",
  },
  {
    name: "Windsurf Village Baia dei Delfini",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Windsurf+Village+Baia+dei+Delfini,+Via+Tramontana+47",
    rating: 4.2,
    reviews: 148,
    description: "Struttura collegata ai principali spot vento.",
  },
  {
    name: "Noleggio Gommoni La Maddalena On Board",
    category: "Windsurf kite",
    zona: "Padule",
    url: "https://maps.google.com/?q=Noleggio+Gommoni+La+Maddalena+On+Board,+Via+Padule,+La+Maddalena",
    rating: 4.6,
    reviews: 78,
    description: "Ottima organizzazione, puntualita e disponibilita.",
  },
  {
    name: "SurfStar center Porto Pollo",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=SurfStar+center+Porto+Pollo,+Localita+Angolo+Azzurro",
    rating: 4.3,
    reviews: 6,
    description: "Centro wingfoil e windsurf attrezzato.",
  },
  {
    name: "Wind Water Sport Center Porto Pollo",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Wind+Water+Sport+Center+Porto+Pollo,+Via+per+campeggio",
    rating: 4.8,
    reviews: 163,
    description: "Per iniziare o perfezionarsi nel windsurf.",
  },
  {
    name: "Extreme Sail A.S.D. - Scuola Windsurf , Wing foil , Catamarani e Derive - Marinella",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Extreme+Sail+ASD+Marinella,+Golfo+di+Marinella",
    rating: 5.0,
    reviews: 53,
    description: "Scuola completa per windsurf e wing foil.",
  },
  {
    name: "Porto Pollo Island Experience",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Porto+Pollo+Island+Experience,+Porto+Pollo",
    rating: 4.6,
    reviews: 45,
    description: "Ottima professionalita degli insegnanti.",
  },
  {
    name: "Wind Kite surf zone Portopollo",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Wind+Kite+surf+zone+Portopollo,+SP98",
    rating: 5.0,
    reviews: 2,
    description: "Scuola specializzata in kite e windsurf.",
  },
  {
    name: "Jungle Surf",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Jungle+Surf,+Via+Nazionale+116",
    rating: 4.4,
    reviews: 158,
    description: "Negozio di riferimento per amanti del windsurf.",
  },
  {
    name: "I W D",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=I+W+D,+Porto+Pollo",
    rating: 4.0,
    reviews: 1,
    description: "Scuola di vela e sport acquatici.",
  },
  {
    name: "Blue Zone Sardinia",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Blue+Zone+Sardinia,+Camping+Baia+Blu+la+Tortuga+Vignola+Mare",
    rating: 4.8,
    reviews: 89,
    description: "Esperienza sportiva completa per sport del vento.",
  },
  {
    name: "Sporting Club Sardinia (Sailing Center)",
    category: "Windsurf kite",
    zona: "Porto Pollo / Palau",
    url: "https://maps.google.com/?q=Sporting+Club+Sardinia+Sailing+Center,+Porto+Pollo",
    rating: 4.5,
    reviews: 76,
    description: "Spiaggia attrezzata con scuola vela e windsurf.",
  },

  // ─── Gelaterie ───────────────────────────────────────────────────────────────
  {
    name: "Gelateria La Finestrella",
    category: "Gelaterie",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Gelateria+La+Finestrella,+Via+Amendola+11,+La+Maddalena",
    rating: 4.8,
    reviews: 1294,
  },
  {
    name: "Gelatissimo",
    category: "Gelaterie",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Gelatissimo,+Via+Amendola+45,+La+Maddalena",
    rating: 4.7,
    reviews: 659,
  },
  {
    name: "Dolci Distrazioni — Via Amendola",
    category: "Gelaterie",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Dolci+Distrazioni,+Via+Giorgio+Amendola+35,+La+Maddalena",
    rating: 4.7,
    reviews: 59,
  },
  {
    name: "Gelateria Ilva",
    category: "Gelaterie",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Gelateria+Ilva,+Piazza+Umberto+I+1,+La+Maddalena",
    rating: 4.0,
    reviews: 118,
  },
  {
    name: "Gelateria Gelatomania",
    category: "Gelaterie",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Gelateria+Gelatomania,+Via+Giuseppe+Garibaldi+82,+La+Maddalena",
    rating: 2.6,
    reviews: 37,
  },
  {
    name: "Crema&Cioccolato",
    category: "Gelaterie",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Crema%26Cioccolato,+Via+XX+Settembre,+La+Maddalena",
    rating: 3.0,
    reviews: 42,
  },
  {
    name: "YO ciok",
    category: "Gelaterie",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=YO+ciok,+Via+Giuseppe+Garibaldi,+La+Maddalena",
    rating: 3.0,
    reviews: 58,
  },
  {
    name: "Dolci Distrazioni — Largo Matteotti (chiuso temporaneamente)",
    category: "Gelaterie",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Dolci+Distrazioni,+Largo+Giacomo+Matteotti+8,+La+Maddalena",
    rating: 4.7,
    reviews: 831,
  },

  // ─── Noleggio gommoni (solo sedi a La Maddalena; esclusi Palau, Caprera, ecc.) ─
  {
    name: "AQUA SPEED Noleggio Gommoni",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=AQUA+SPEED+Noleggio+Gommoni,+Via+Amendola,+La+Maddalena",
    rating: 4.4,
    reviews: 33,
  },
  {
    name: "Bi.Pe.De.",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Bi.Pe.De.,+Via+Padule,+La+Maddalena",
    rating: 3.8,
    reviews: 12,
  },
  {
    name: "Blue Dolphin Escursioni La Maddalena",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Blue+Dolphin+Escursioni,+Via+Padule,+La+Maddalena",
    rating: 4.9,
    reviews: 70,
  },
  {
    name: "Boat Service",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Boat+Service,+Localit%C3%A0+la+Ricciolina,+La+Maddalena",
    rating: 5.0,
    reviews: 5,
  },
  {
    name: "CILIEGIO 2 — Escursioni in barca La Maddalena",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=CILIEGIO+2+Escursioni,+Via+Padule+60,+La+Maddalena",
    rating: 5.0,
    reviews: 80,
  },
  {
    name: "Ecomar — Affitto posti barca",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Ecomar+Affitto+Posti+Barca,+Via+Regina+Margherita+11,+La+Maddalena",
    rating: 4.5,
    reviews: 20,
  },
  {
    name: "Ecomar Noleggio Gommoni La Maddalena",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Ecomar+Noleggio+Gommoni,+Regione+Nido+d%27Aquila+10,+La+Maddalena",
    rating: 4.7,
    reviews: 32,
  },
  {
    name: "Elena Tour Navigazioni — Escursioni e noleggio",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Elena+Tour+Navigazioni,+Via+Amendola,+La+Maddalena",
    rating: 4.6,
    reviews: 944,
  },
  {
    name: "Emerald Freedom La Maddalena",
    category: "Noleggio gommoni",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Emerald+Freedom+La+Maddalena,+Via+Cala+Chiesa+52,+La+Maddalena",
    rating: 5.0,
    reviews: 300,
  },
  {
    name: "ENAVIGOSARDINIA — Gite alle isole",
    category: "Noleggio gommoni",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=ENAVIGOSARDINIA,+Via+Lungomare+A.+Doria+7B,+La+Maddalena",
    rating: 4.9,
    reviews: 114,
  },
  {
    name: "Enjoy La Maddalena Noleggio Gommoni",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Enjoy+La+Maddalena+Noleggio+Gommoni,+Via+Padule,+La+Maddalena",
    rating: 4.8,
    reviews: 72,
  },
  {
    name: "Exclusive Boats — La Maddalena boat rental",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Exclusive+Boats+La+Maddalena,+Via+Amendola,+La+Maddalena",
    rating: 4.9,
    reviews: 42,
  },
  {
    name: "F.R. Nautica — Noleggio gommoni senza patente",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=F.R.+Nautica+Noleggio+Gommoni,+Via+Padule,+La+Maddalena",
    rating: 5.0,
    reviews: 44,
  },
  {
    name: "Freemind Experience — Escursioni e noleggio gommoni",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Freemind+Experience,+Via+Padule,+La+Maddalena",
    rating: 5.0,
    reviews: 414,
  },
  {
    name: "Gipsy Motor Boat — La Maddalena Excursions",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Gipsy+Motor+Boat,+Via+Padule,+La+Maddalena",
    rating: 5.0,
    reviews: 79,
  },
  {
    name: "Grace boat — Escursioni e noleggio La Maddalena",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Grace+boat+Escursioni,+Via+Padule,+La+Maddalena",
    rating: 5.0,
    reviews: 29,
  },
  {
    name: "Il Porticciolo — Noleggio gommoni e posti barca",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Il+Porticciolo+Noleggio+Gommoni,+Via+Padule,+La+Maddalena",
    rating: 4.8,
    reviews: 52,
  },
  {
    name: "Island Marine La Maddalena — noleggio gommone con skipper",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Island+Marine+La+Maddalena,+Via+Eleonora+D%27Arborea+3,+La+Maddalena",
    rating: 5.0,
    reviews: 1,
  },
  {
    name: "La Maddalena in gommone (F.M. Service)",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=La+Maddalena+in+gommone+F.M.+Service,+Via+Padule,+La+Maddalena",
    rating: 5.0,
    reviews: 88,
  },
  {
    name: "Marina Dei Giardinelli La Maddalena",
    category: "Noleggio gommoni",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Marina+Dei+Giardinelli,+Localit%C3%A0+Giardinelli,+La+Maddalena",
    rating: 4.5,
    reviews: 19,
  },
  {
    name: "Marina Del Ponte",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Marina+Del+Ponte,+Via+Benvenuto+Cellini,+La+Maddalena",
    rating: 4.4,
    reviews: 106,
  },
  {
    name: "Marinella IV — Escursioni in barca",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Marinella+IV,+Via+Amendola+10,+La+Maddalena",
    rating: 4.9,
    reviews: 102,
  },
  {
    name: "Mas Que Nada — noleggio gommoni",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Mas+Que+Nada+noleggio+gommoni,+La+Maddalena",
    rating: 5.0,
    reviews: 16,
  },
  {
    name: "MD Service Nautica — Noleggio gommoni",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=MD+Service+Nautica+Noleggio+Gommoni,+Via+Ulisse,+La+Maddalena",
    rating: 4.6,
    reviews: 173,
  },
  {
    name: "Memo — Escursioni e gite in gommone",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Memo+escursioni+gite+gommone,+Piazza+Villamarina+4,+La+Maddalena",
    rating: 4.8,
    reviews: 20,
  },
  {
    name: "Motoscafo Free Whale — Noleggio barche La Maddalena",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Motoscafo+Free+Whale,+Via+Padule+7,+La+Maddalena",
    rating: 4.3,
    reviews: 6,
  },
  {
    name: "Noleggio gommoni con e senza conducente — rent zodiac",
    category: "Noleggio gommoni",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Noleggio+gommoni+rent+zodiac,+banchina+Punta+Chiara,+La+Maddalena",
    rating: 1.8,
    reviews: 5,
  },
  {
    name: "Noleggio gommoni con e senza conducente — Sea Escape",
    category: "Noleggio gommoni",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Sea+Escape+noleggio+gommoni,+Loc.+Cala+Peticchia,+La+Maddalena",
    rating: 4.9,
    reviews: 26,
  },
  {
    name: "Noleggio gommoni Fratelli Cuccu",
    category: "Noleggio gommoni",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Noleggio+gommoni+Fratelli+Cuccu,+Banchina+Poste,+La+Maddalena",
    rating: 4.1,
    reviews: 29,
  },
  {
    name: "Noleggio gommoni La Maddalena — Antares Rentals",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Antares+Rentals+noleggio+gommoni,+Via+Benvenuto+Cellini,+La+Maddalena",
    rating: 5.0,
    reviews: 4,
  },
  {
    name: "Noleggio Gommoni — Nautica Sagiel",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Nautica+Sagiel+Noleggio+Gommoni,+Via+Ulisse,+La+Maddalena",
    rating: 5.0,
    reviews: 183,
  },
  {
    name: "Noleggio Gommoni e affitto posti barca — Ecomar (Punta Chiara)",
    category: "Noleggio gommoni",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Ecomar+Noleggio+Gommoni,+banchina+Punta+Chiara,+La+Maddalena",
    rating: 4.8,
    reviews: 53,
  },
  {
    name: "Noleggio Gommoni Karma",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Noleggio+Gommoni+Karma,+Via+Padule,+La+Maddalena",
    rating: 5.0,
    reviews: 352,
  },
  {
    name: "Noleggio Gommoni La Maddalena — Eagle Marine",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Eagle+Marine+Noleggio+Gommoni,+Regione+Nido+d%27Aquila,+La+Maddalena",
    rating: 4.9,
    reviews: 92,
  },
  {
    name: "Noleggio Gommoni La Maddalena — H2Omarine",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=H2Omarine+Noleggio+Gommoni,+Via+Padule,+La+Maddalena",
    rating: 5.0,
    reviews: 165,
  },
  {
    name: "Noleggio Gommoni La Maddalena — On Board",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=On+Board+Noleggio+Gommoni,+Via+Padule,+La+Maddalena",
    rating: 4.6,
    reviews: 78,
  },
  {
    name: "Noleggio Gommoni Lo Squalo Bianco",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Lo+Squalo+Bianco+Noleggio+Gommoni,+Via+Ulisse+1,+La+Maddalena",
    rating: 4.9,
    reviews: 500,
  },
  {
    name: "Noleggio Gommoni Passion Marine La Maddalena",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Passion+Marine+Noleggio+Gommoni,+Regione+Nido+d%27Aquila,+La+Maddalena",
    rating: 5.0,
    reviews: 37,
  },
  {
    name: "Nautilus Noleggio Gommoni — Anna Rosa Loi",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Nautilus+Noleggio+Gommoni,+Piazza+Umberto+I,+La+Maddalena",
    rating: 4.4,
    reviews: 48,
  },
  {
    name: "Paquito Escursioni",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Paquito+Escursioni,+Via+Stefano+Palmas,+La+Maddalena",
    rating: 5.0,
    reviews: 7,
  },
  {
    name: "Porto Cala Mangiavolpe",
    category: "Noleggio gommoni",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Porto+Cala+Mangiavolpe,+Lungomare+Via+Amendola,+La+Maddalena",
    rating: 4.5,
    reviews: 905,
  },
  {
    name: "Posti barca Cala Mangiavolpe",
    category: "Noleggio gommoni",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Posti+Barca+Cala+Mangiavolpe,+Lungomare+Via+Amendola,+La+Maddalena",
    rating: 5.0,
    reviews: 5,
  },
  {
    name: "Sardegna Yacht Charter Tour La Maddalena",
    category: "Noleggio gommoni",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Sardegna+Yacht+Charter+Tour,+Via+Lungomare+A.+Doria+39,+La+Maddalena",
    rating: 5.0,
    reviews: 4,
  },
  {
    name: "Sardinia Sea Excursions — La Maddalena boat trips",
    category: "Noleggio gommoni",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Sardinia+Sea+Excursions,+Cala+Gavetta,+La+Maddalena",
    rating: 4.9,
    reviews: 98,
  },
  {
    name: "Timi Boat — Rent Yacht",
    category: "Noleggio gommoni",
    zona: "Padule",
    url: "https://maps.google.com/?q=Timi+Boat+Rent+Yacht,+Via+Balilla+11,+La+Maddalena",
    rating: 3.7,
    reviews: 3,
  },
  {
    name: "Vale Boat e Travel — Gite in barca",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Vale+Boat+e+Travel,+Via+Amendola+87,+La+Maddalena",
    rating: 5.0,
    reviews: 36,
  },
  {
    name: "Veliero Dolce Vita La Maddalena",
    category: "Noleggio gommoni",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Veliero+Dolce+Vita,+Via+Indipendenza+1,+La+Maddalena",
    rating: 4.9,
    reviews: 172,
  },

  // ─── Noleggio scooter e bike ─────────────────────────────────────────────────
  {
    name: "Rent Experience — Slow Travel (e-bike, scooter, kayak) — chiuso temporaneamente",
    category: "Noleggio scooter e bike",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Rent+Experience+Slow+Travel+La+Maddalena,+porto+La+Maddalena",
    rating: 4.9,
    reviews: 74,
  },
  {
    name: "Mega Motors — Moto, bike, MTB, e-bike e quad",
    category: "Noleggio scooter e bike",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Mega+Motors+Noleggio,+Via+Amendola+2,+La+Maddalena",
    rating: 4.8,
    reviews: 131,
  },
  {
    name: "189 Garage — Noleggio scooter",
    category: "Noleggio scooter e bike",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=189+Garage+noleggio+scooter,+Via+Amendola+17,+La+Maddalena",
    rating: 4.3,
    reviews: 213,
  },
  {
    name: "Noleggio Rondinella La Maddalena",
    category: "Noleggio scooter e bike",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Noleggio+Rondinella,+Via+Amendola+41,+La+Maddalena",
    rating: 4.5,
    reviews: 25,
  },
  {
    name: "Noleggio F.lli Cuccu — Auto, scooter, quad, gommoni, e-bike",
    category: "Noleggio scooter e bike",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Noleggio+Flli+Cuccu,+Via+Amendola+45,+La+Maddalena",
    rating: 4.6,
    reviews: 389,
  },
  {
    name: "Nicolsport",
    category: "Noleggio scooter e bike",
    zona: "Centro Storico",
    url: "https://maps.google.com/?q=Nicolsport,+Via+Amendola+16,+La+Maddalena",
    rating: 3.5,
    reviews: 226,
  },

  // ─── Banche & ATM ────────────────────────────────────────────────────────────
  ...serviziBanche,

  // ─── Trasporti ───────────────────────────────────────────────────────────────
  ...serviziTrasporti,

  // ─── Emergenze ───────────────────────────────────────────────────────────────
  ...serviziEmergenze,

  // ─── Musei (solo arcipelago: La Maddalena e Caprera) ─────────────────────────
  ...serviziMusei,

  // ─── Sentieri Caprera (luoghi, spiagge e punti panoramici) ───────────────────
  ...serviziSentieriCaprera,
];
