import type { Servizio } from "./servizi";

/** Ristoranti e pizzerie (estratti da elenco Google Maps). */
export const serviziRistoranti: readonly Servizio[] = [
  {
    id: "rest_01",
    name: "Pizzeria Ristorante La Marachella",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.408893, 41.214897],
    url: "https://maps.google.com/?q=Pizzeria+Ristorante+La+Marachella,+Via+Enrico+Dandolo+9,+La+Maddalena",
    rating: 4.8,
    reviews: 660,
    description: "Pizza · Via Enrico Dandolo, 9.",
    isFavorite: false,
    maddiNote:
      "Prova la pizza gourmet e chiedi un tavolo esterno nelle serate ventilate.",
  },
  {
    name: "Pizzeria Civico 49",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40788, 41.21418],
    url: "https://maps.google.com/?q=Pizzeria+Civico+49,+Via+Giuseppe+Garibaldi+59,+La+Maddalena",
    rating: 4.6,
    reviews: 1145,
    description: "Pizza · Via Giuseppe Garibaldi, 59.",
  },
  {
    name: "Ristorante Pizzeria Sergent Pepper's La Maddalena",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40686, 41.212852],
    url: "https://maps.google.com/?q=Ristorante+Pizzeria+Sergent+Peppers,+Via+Giordano+Bruno+1,+La+Maddalena",
    rating: 4.4,
    reviews: 2223,
    description: "Italiana · Via Giordano Bruno, 1.",
  },
  {
    name: "I Capatosta",
    category: "Ristoranti",
    zona: "Padule",
    coordinates: [9.41422, 41.218006],
    url: "https://maps.google.com/?q=I+Capatosta,+Piazza+Bambino+Gesu+12,+La+Maddalena",
    rating: 4.5,
    reviews: 1333,
    description: "Pizza · Piazza Bambino Gesù, 12.",
  },
  {
    name: "Speedy Pizza (La Maddalena)",
    category: "Ristoranti",
    zona: "Padule",
    coordinates: [9.42067, 41.218939],
    url: "https://maps.google.com/?q=Speedy+Pizza,+Via+Indipendenza+38,+La+Maddalena",
    rating: 4.8,
    reviews: 298,
    description: "Pizza · Via Indipendenza, 38.",
  },
  {
    name: "Pizzeria La Mula's",
    category: "Ristoranti",
    zona: "Padule",
    coordinates: [9.406656, 41.216285],
    url: "https://maps.google.com/?q=Pizzeria+La+Mulas,+Via+Balbo+47,+La+Maddalena",
    rating: 4.8,
    reviews: 538,
    description: "Pizza · Via Balbo, 47.",
  },
  {
    name: "Pizzeria-Friggitoria Cavaliere",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.41049, 41.215109],
    url: "https://maps.google.com/?q=Pizzeria+Friggitoria+Cavaliere,+Piazza+Umberto+I+6,+La+Maddalena",
    rating: 4.6,
    reviews: 288,
    description: "Pizza · Piazza Umberto I, 6.",
  },
  {
    name: "Ristorante Pizzeria Roby's dal 1991",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40682, 41.21237],
    url: "https://maps.google.com/?q=Ristorante+Pizzeria+Robys,+Via+Amendola+2B,+La+Maddalena",
    rating: 4.3,
    reviews: 828,
    description: "Ristorante · Via Amendola, 2B.",
  },
  {
    name: "Pizzeria i quattro venti la Maddalena",
    category: "Ristoranti",
    zona: "Padule",
    coordinates: [9.41716, 41.22044],
    url: "https://maps.google.com/?q=Pizzeria+i+quattro+venti,+Via+Cala+Chiesa+36,+La+Maddalena",
    rating: 4.4,
    reviews: 55,
    description: "Pizza · Via Cala Chiesa, 36.",
  },
  {
    name: "U Campu Du Pastori-Osteria",
    category: "Ristoranti",
    zona: "Padule",
    coordinates: [9.413027, 41.216228],
    url: "https://maps.google.com/?q=U+Campu+Du+Pastori,+Via+Quarto+1,+La+Maddalena",
    rating: 4.6,
    reviews: 1106,
    description: "Ristorante · Via Quarto, 1.",
  },
  {
    name: "MaMa Pizza",
    category: "Ristoranti",
    zona: "Moneta",
    coordinates: [9.387849, 41.213093],
    url: "https://maps.google.com/?q=MaMa+Pizza,+Localita+Nido+dAquila,+La+Maddalena",
    rating: 4.1,
    reviews: 312,
    description: "Pizza · Località Nido d'Aquila.",
  },
  {
    name: "Ristorante L'aragosta",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40786, 41.213779],
    url: "https://maps.google.com/?q=Ristorante+L+Aragosta,+Via+Amendola+38,+La+Maddalena",
    rating: 4.0,
    reviews: 1163,
    description: "Italiana · Via Amendola, 38.",
  },
  {
    name: "Pizzeria da Vito",
    category: "Ristoranti",
    zona: "Padule",
    coordinates: [9.43012, 41.219979],
    url: "https://maps.google.com/?q=Pizzeria+da+Vito,+Via+Benvenuto+Cellini+9,+La+Maddalena",
    rating: 4.5,
    reviews: 251,
    description: "Pizza · Via Benvenuto Cellini, 9.",
  },
  {
    name: "Birreria Mezzo Passo",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40537, 41.212791],
    url: "https://maps.google.com/?q=Birreria+Mezzo+Passo,+Corso+Vittorio+Emanuele+1,+La+Maddalena",
    rating: 4.4,
    reviews: 306,
    description: "Ristorante · Corso Vittorio Emanuele, 1.",
  },
  {
    name: "Mafalda Pizzeria",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.407569, 41.213662],
    url: "https://maps.google.com/?q=Mafalda+Pizzeria,+Via+Giuseppe+Garibaldi,+La+Maddalena",
    rating: 4.5,
    reviews: 48,
    description: "Pizza · Via Giuseppe Garibaldi.",
  },
  {
    name: "Il Gabbiano Pizza & Food Lounge",
    category: "Ristoranti",
    zona: "Cala Gavetta",
    coordinates: [9.4016, 41.210935],
    url: "https://maps.google.com/?q=Il+Gabbiano+Pizza+Food+Lounge,+Via+Giulio+Cesare+20,+La+Maddalena",
    rating: 3.4,
    reviews: 72,
    description: "Ristorante · Via Giulio Cesare, 20.",
  },
  {
    name: "The Bistrot",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.4067, 41.212338],
    url: "https://maps.google.com/?q=The+Bistrot,+Via+Amendola+71,+La+Maddalena",
    rating: 4.3,
    reviews: 168,
    description: "Bistrò · Via Amendola, 71.",
  },
  {
    name: "Bombopizza",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.405053, 41.212907],
    url: "https://maps.google.com/?q=Bombopizza,+Corso+Vittorio+Emanuele,+La+Maddalena",
    rating: 4.2,
    reviews: 157,
    description: "Pizza · Corso Vittorio Emanuele.",
  },
  {
    name: "Ristorante Caprera",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.405185, 41.213205],
    url: "https://maps.google.com/?q=Ristorante+Caprera,+Via+Tommaso+Zonza+3,+La+Maddalena",
    rating: 4.6,
    reviews: 366,
    description: "Ristorante · Via Tommaso Zonza, 3.",
  },
  {
    name: "Garden Sea – Ristorante, Pizzeria e Cucina Gluten Free",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.407569, 41.213662],
    url: "https://maps.google.com/?q=Garden+Sea+Ristorante+Pizzeria,+Via+Giuseppe+Garibaldi+79,+La+Maddalena",
    rating: 3.8,
    reviews: 697,
    description: "Pesce · Via Giuseppe Garibaldi, 79/100.",
  },
  {
    name: "Trattoria Friggitoria da Remo",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40789, 41.213871],
    url: "https://maps.google.com/?q=Trattoria+Friggitoria+da+Remo,+Via+Amendola+43,+La+Maddalena",
    rating: 4.2,
    reviews: 255,
    description: "Italiana · Via Amendola, 43.",
  },
  {
    name: "Pizzeria Gastronomia Bar Kicco loco",
    category: "Ristoranti",
    zona: "Padule",
    coordinates: [9.417407, 41.21748],
    url: "https://maps.google.com/?q=Pizzeria+Gastronomia+Bar+Kicco+loco,+Via+Aldo+Moro+5,+La+Maddalena",
    rating: 4.0,
    reviews: 246,
    description: "Pizza · Via Aldo Moro, 5.",
  },
  {
    name: "La Locanda del Mirto",
    category: "Ristoranti",
    zona: "Moneta",
    coordinates: [9.42224, 41.23807],
    url: "https://maps.google.com/?q=La+Locanda+del+Mirto,+Localita+Punta+della+Gatta,+La+Maddalena",
    rating: 4.3,
    reviews: 797,
    description: "Ristorante · Località Punta della Gatta.",
  },
  {
    name: "Ristorante Perla Blu",
    category: "Ristoranti",
    zona: "Cala Gavetta",
    coordinates: [9.402785, 41.212799],
    url: "https://maps.google.com/?q=Ristorante+Perla+Blu,+Piazza+des+Geneys+7,+La+Maddalena",
    rating: 3.9,
    reviews: 670,
    description: "Italiana · Piazza des Geneys, 7.",
  },
  {
    name: "Trattoria Vecchia ILVA",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.405975, 41.213144],
    url: "https://maps.google.com/?q=Trattoria+Vecchia+ILVA,+Largo+Giacomo+Matteotti+1,+La+Maddalena",
    rating: 4.1,
    reviews: 552,
    description: "Ristorante · Largo Giacomo Matteotti, 1.",
  },
  {
    name: "Ristorante L' Avventura",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40634, 41.21225],
    url: "https://maps.google.com/?q=Ristorante+L+Avventura,+Via+Amendola+21,+La+Maddalena",
    rating: 4.2,
    reviews: 773,
    description: "Ristorante di pesce · Via Amendola, 21.",
  },
  {
    name: "Il Ghiottone - La Maddalena",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40431, 41.212916],
    url: "https://maps.google.com/?q=Il+Ghiottone,+Via+Guglielmo+Oberdan+5,+La+Maddalena",
    rating: 4.3,
    reviews: 428,
    description: "Ristorante · Via Guglielmo Oberdan, 5.",
  },
  {
    name: "Gastronomia, Rosticceria, Pizza al taglio, Paninoteca da Pio",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.403163, 41.214072],
    url: "https://maps.google.com/?q=Paninoteca+da+Pio,+Via+Agostino+Millelire,+La+Maddalena",
    rating: 4.4,
    reviews: 62,
    description: "Gastronomia · Via Agostino Millelire.",
  },
  {
    name: "Trattoria Dal Genovese 2.0",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40755, 41.21402],
    url: "https://maps.google.com/?q=Trattoria+Dal+Genovese+2.0,+Via+Manfredo+Fanti+10,+La+Maddalena",
    rating: 4.1,
    reviews: 461,
    description: "Ristorante ligure · Via Manfredo Fanti, 10.",
  },
  {
    name: "Ristorante Stazzo Il Rifugio dei Peccatori",
    category: "Ristoranti",
    zona: "Moneta",
    coordinates: [9.432242, 41.221451],
    url: "https://maps.google.com/?q=Stazzo+Il+Rifugio+dei+Peccatori,+Via+Giuseppe+Mary,+La+Maddalena",
    rating: 4.2,
    reviews: 797,
    description: "Ristorante sardo · Via Mary G.",
  },
  {
    name: "I Curciareddhi",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40323, 41.213561],
    url: "https://maps.google.com/?q=I+Curciareddhi,+Piazza+Principe+Tommaso+11,+La+Maddalena",
    rating: 4.0,
    reviews: 420,
    description: "Ristorante · Piazza Principe Tommaso, 11.",
  },
  {
    name: "Il Tramonto di Abbatoggia | Ristorante a La Maddalena",
    category: "Ristoranti",
    zona: "Moneta",
    coordinates: [9.404745, 41.251891],
    url: "https://maps.google.com/?q=Il+Tramonto+di+Abbatoggia,+Localita+Abbatoggia,+La+Maddalena",
    rating: 3.9,
    reviews: 120,
    description: "Italiana · Località Abbatoggia.",
  },
  {
    name: "L’Antica Isola",
    category: "Ristoranti",
    zona: "Moneta",
    coordinates: [9.387849, 41.213093],
    url: "https://maps.google.com/?q=L+Antica+Isola,+Localita+Nido+dAquila,+La+Maddalena",
    rating: 3.7,
    reviews: 27,
    description: "Ristorante · Località Nido d'Aquila.",
  },
  {
    name: "Gastronomia da Anselmo",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.405657, 41.213269],
    url: "https://maps.google.com/?q=Gastronomia+da+Anselmo,+Via+Ilva+6,+La+Maddalena",
    rating: 4.5,
    reviews: 265,
    description: "Gastronomia · Via Ilva, 6.",
  },
  {
    name: "Ristorante & Sushi Lab",
    category: "Ristoranti",
    zona: "Padule",
    coordinates: [9.413015, 41.216191],
    url: "https://maps.google.com/?q=Ristorante+Sushi+Lab,+Via+Quarto+4,+La+Maddalena",
    rating: 4.1,
    reviews: 413,
    description: "Pesce · Via Quarto, 4.",
  },
  {
    name: "Pizza in Piazza",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.406215, 41.212181],
    url: "https://maps.google.com/?q=Pizza+in+Piazza,+Via+Amendola+48,+La+Maddalena",
    rating: 3.7,
    reviews: 83,
    description: "Pizza · Via Amendola, 48.",
  },
  {
    id: "rest_40",
    name: "Zi Antò",
    category: "Ristoranti",
    zona: "Cala Gavetta",
    coordinates: [9.385298, 41.211454],
    url: "https://maps.google.com/?q=Zi+Anto,+Localita+Punta+Tegge,+La+Maddalena",
    rating: 4.3,
    reviews: 1260,
    description: "Ristorante · Località Punta Tegge.",
    isFavorite: true,
    maddiNote:
      "Prenota al tramonto: vista spettacolare e atmosfera perfetta per una cena speciale.",
  },
  {
    name: "Pizzeria Taz",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.405657, 41.213269],
    url: "https://maps.google.com/?q=Pizzeria+Taz,+Via+Ilva+6,+La+Maddalena",
    rating: 4.5,
    reviews: 153,
    description: "Pizza · Via Ilva, 6.",
  },
  {
    name: "Osteria Chèz Cocò",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.405381, 41.212402],
    url: "https://maps.google.com/?q=Osteria+Chez+Coco,+Via+Principe+di+Napoli+7,+La+Maddalena",
    rating: 4.4,
    reviews: 453,
    description: "Ristorante · Via Principe di Napoli, 7.",
  },
  {
    name: "Arutas Bistrot & Cocktail Bar",
    category: "Ristoranti",
    zona: "Centro Storico",
    coordinates: [9.40479, 41.212991],
    url: "https://maps.google.com/?q=Arutas+Bistrot+Cocktail+Bar,+Corso+Vittorio+Emanuele+28,+La+Maddalena",
    rating: 4.7,
    reviews: 166,
    description: "Tapas bar · Corso Vittorio Emanuele, 28.",
  },
  {
    name: "Ristorante L'Olimpo Nido d'aquila pesce a km0",
    category: "Ristoranti",
    zona: "Moneta",
    coordinates: [9.394813, 41.222739],
    url: "https://maps.google.com/?q=Ristorante+LOlimpo+Nido+dAquila,+SP114,+La+Maddalena",
    rating: 4.5,
    reviews: 185,
    description: "Pesce · SP114.",
  },
].map((servizio) => ({ isFavorite: false, maddiNote: "", ...(servizio as Servizio) }));
