import type { Servizio } from "./servizi";

/** Spiagge dell'arcipelago da elenco utente (senza immagini stock). */
export const serviziSpiagge: readonly Servizio[] = [
  {
    name: "Spiaggia di Cala Spalmatore",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Spalmatore,+La+Maddalena",
    rating: 4.4,
    reviews: 1368,
    description: "Tratto sabbioso con acque cristalline e un bar.",
  },
  {
    name: "Spiaggia di Punta Tegge",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+di+Punta+Tegge,+Localit%C3%A0+Punta+Tegge+3,+La+Maddalena",
    rating: 4.6,
    reviews: 2390,
    description: "Spiaggia pittoresca in baia rocciosa.",
  },
  {
    name: "Spiaggia Monti d'à Rena",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+Monti+d%27a+Rena,+La+Maddalena",
    rating: 4.6,
    reviews: 1022,
  },
  {
    name: "Spiaggia di Punta Tegge",
    category: "Spiagge",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=Spiaggia+di+Punta+Tegge,+Localit%C3%A0+Punta+Tegge+3,+La+Maddalena",
    rating: 4.6,
    reviews: 2390,
    description:
      "Cala rocciosa, spiagge note, immersioni.",
  },
  {
    name: "Spiaggia di Cala Lunga",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Lunga,+Isola+di+La+Maddalena",
    rating: 4.5,
    reviews: 223,
    description: "Isola Maddalena.",
  },
  {
    name: "Spiaggia dello Strangolato",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+dello+Strangolato,+La+Maddalena",
    rating: 4.5,
    reviews: 418,
  },
  {
    name: "Spiaggia di Cala Coticcio",
    category: "Spiagge",
    zona: "Caprera",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Coticcio,+Caprera",
    rating: 4.7,
    reviews: 2375,
    description: "Caletta suggestiva tra scogliere.",
  },
  {
    name: "Spiaggia di Bassa Trinita",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+di+Bassa+Trinita,+La+Maddalena",
    rating: 4.7,
    reviews: 1523,
    description:
      "Spiaggia con 3 calette e sentiero naturale.",
  },
  {
    name: "Spiaggia I due Mari",
    category: "Spiagge",
    zona: "Caprera",
    url: "https://maps.google.com/?q=Spiaggia+I+due+Mari,+Caprera",
    rating: 4.5,
    reviews: 1437,
  },
  {
    name: "Spiaggia Testa del Polpo",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+Testa+del+Polpo,+La+Maddalena",
    rating: 4.6,
    reviews: 1655,
    description:
      "Tratto di sabbia bianca con scogli affioranti.",
  },
  {
    name: "Spiaggia Cala d'Inferno",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+Cala+d%27Inferno,+La+Maddalena",
    rating: 4.1,
    reviews: 57,
  },
  {
    name: "Spiaggia del Costone",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+del+Costone,+La+Maddalena",
    rating: 4.5,
    reviews: 371,
  },
  {
    name: "Spiaggia del Costone",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+del+Costone,+La+Maddalena",
    rating: 4.5,
    reviews: 371,
    description:
      "Tra le più sottovalutate e meno affollate del versante nord.",
  },
  {
    name: "Spiaggia dell'Alberello",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+dell%27Alberello,+Giardinelli,+La+Maddalena",
    rating: 4.6,
    reviews: 187,
    description: "Località Giardinelli.",
  },
  {
    name: "Spiaggia Punta Rossa Corsara",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+Punta+Rossa+Corsara,+Strada+Padulacciu,+La+Maddalena",
    rating: 4.7,
    reviews: 141,
  },
  {
    name: "Spiaggia del Cardellino",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+del+Cardellino,+La+Maddalena",
    rating: 4.6,
    reviews: 504,
    description: "Isola Maddalena.",
  },
  {
    name: "Spiaggia dei marinai",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+dei+marinai,+La+Maddalena",
    rating: 4.6,
    reviews: 15,
    description: "Unnamed Road, 07024.",
  },
  {
    name: "Spiaggia La Scogliera",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+La+Scogliera,+La+Maddalena",
    rating: 4.5,
    reviews: 15,
  },
  {
    name: "Spiaggia di Cala Garibaldi",
    category: "Spiagge",
    zona: "Caprera",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Garibaldi,+Caprera",
    rating: 4.2,
    reviews: 845,
  },
  {
    name: "Spiaggia Bassa Trinità",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+Bassa+Trinit%C3%A0,+La+Maddalena",
    rating: 4.7,
    reviews: 278,
  },
  {
    name: "Spiaggia di Cala Andreani",
    category: "Spiagge",
    zona: "Caprera",
    url: "https://maps.google.com/?q=Spiaggia+di+Cala+Andreani,+Caprera",
    rating: 4.8,
    reviews: 75,
  },
  {
    name: "Spiaggia di Porto Palma",
    category: "Spiagge",
    zona: "Caprera",
    url: "https://maps.google.com/?q=Spiaggia+di+Porto+Palma,+Caprera",
    rating: 4.6,
    reviews: 233,
  },
  {
    name: "La Maddalena Spiaggia",
    category: "Spiagge",
    zona: "Cala Gavetta",
    url: "https://maps.google.com/?q=La+Maddalena+Spiaggia,+La+Maddalena",
    rating: 3.9,
    reviews: 275,
  },
  {
    name: "Spiaggia di Ricciolina",
    category: "Spiagge",
    zona: "Padule",
    url: "https://maps.google.com/?q=Spiaggia+di+Ricciolina,+Localit%C3%A0+la+Ricciolina,+La+Maddalena",
    rating: 3.2,
    reviews: 13,
  },
  {
    name: "Cala Andreani",
    category: "Spiagge",
    zona: "Caprera",
    url: "https://maps.google.com/?q=Cala+Andreani,+Caprera",
    rating: 4.7,
    reviews: 1265,
  },
  {
    name: "Spiaggia di Abbatoggia",
    category: "Spiagge",
    zona: "Moneta",
    url: "https://maps.google.com/?q=Spiaggia+di+Abbatoggia,+La+Maddalena",
    rating: 4.3,
    reviews: 35,
  },
];
